from typing import Protocol, Sequence, Optional
from app.infrastructure.models.portfolio_model import Portfolio

class IPortfolioRepository(Protocol):
    async def create(self, data: dict) -> Portfolio: ...
    async def get(self, portfolio_id: int) -> Optional[Portfolio]: ...
    async def list(self, skip: int = 0, limit: int = 50, q: str | None = None) -> Sequence[Portfolio]: ...
    async def update(self, portfolio_id: int, data: dict, concurrency_guid: str) -> Portfolio: ...
    async def soft_delete(self, portfolio_id: int, concurrency_guid: str) -> Portfolio: ...
