from typing import Protocol, Sequence, Optional
from app.infrastructure.models.program_model import Program

class IProgramRepository(Protocol):
    async def create(self, data: dict) -> Program: ...
    async def get(self, program_id: int) -> Optional[Program]: ...
    async def list_by_portfolio(self, portfolio_id: int, skip: int = 0, limit: int = 50, q: str | None = None) -> Sequence[Program]: ...
    async def update(self, program_id: int, data: dict, concurrency_guid: str) -> Program: ...
    async def soft_delete(self, program_id: int, concurrency_guid: str) -> Program: ...
