from abc import ABC, abstractmethod
from typing import Optional, Sequence, Mapping, Any
from app.infrastructure.models.project_model import Project

class IProjectRepository(ABC):
    @abstractmethod
    async def list(self, limit: int = 50, offset: int = 0) -> Sequence[Project]: ...
    @abstractmethod
    async def get_by_id(self, project_id: int) -> Optional[Project]: ...
    @abstractmethod
    async def create(self, data: Mapping[str, Any]) -> Project: ...
    @abstractmethod
    async def update_partial(self, project_id: int, fields: Mapping[str, Any]) -> Optional[Project]: ...
    @abstractmethod
    async def delete(self, project_id: int) -> bool: ...
    @abstractmethod
    async def soft_delete_and_return(self, project_id: int) -> Optional[Project]: ...
