
from abc import ABC, abstractmethod
from typing import Optional, Sequence
from app.infrastructure.models.user_model import User as UserModel

class IUserRepository(ABC):
    @abstractmethod
    async def get_by_id(self, id_: int) -> Optional[UserModel]: ...
    @abstractmethod
    async def get_by_username(self, username: str) -> Optional[UserModel]: ...
    @abstractmethod
    async def get_by_email(self, email: str) -> Optional[UserModel]: ...
    @abstractmethod
    async def create(self, user: UserModel) -> UserModel: ...
    @abstractmethod
    async def list(self, limit: int = 50, offset: int = 0) -> Sequence[UserModel]: ...
    @abstractmethod
    async def update_fields(self, id_: int, fields: dict) -> Optional[UserModel]: ...
    @abstractmethod
    async def delete_user_and_return(self, id_: int) -> Optional[UserModel]: ...
