"""verify: 2026-03-19T19:21:02Z

Revision ID: 03c7c0849f2b
Revises: 69ef7e977681
Create Date: 2026-03-19 22:21:03.594627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c7c0849f2b'
down_revision: Union[str, Sequence[str], None] = '69ef7e977681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
