"""auto: 2026-04-05T00:00:39Z

Revision ID: 0689ea77de52
Revises: 3a79e6f2b52f
Create Date: 2026-04-05 03:00:40.273911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0689ea77de52'
down_revision: Union[str, Sequence[str], None] = '3a79e6f2b52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
