"""verify: 2026-03-19T16:01:14Z

Revision ID: 072113fe2c64
Revises: 26674c9eeb1f
Create Date: 2026-03-19 19:01:15.833938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072113fe2c64'
down_revision: Union[str, Sequence[str], None] = '26674c9eeb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
