"""verify: 2026-01-18T15:45:05Z

Revision ID: 085baa4574f0
Revises: 1912bb5a00a8
Create Date: 2026-01-18 15:45:06.003655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085baa4574f0'
down_revision: Union[str, Sequence[str], None] = '1912bb5a00a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
