"""verify: 2026-04-06T13:56:44Z

Revision ID: 15cdcb9be662
Revises: 4f8445f99e6e
Create Date: 2026-04-06 16:56:45.651376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cdcb9be662'
down_revision: Union[str, Sequence[str], None] = '4f8445f99e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
