"""auto: 2026-01-18T15:45:04Z

Revision ID: 1912bb5a00a8
Revises: df06ec6d7f39
Create Date: 2026-01-18 15:45:04.748389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1912bb5a00a8'
down_revision: Union[str, Sequence[str], None] = 'df06ec6d7f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
