"""verify: 2026-03-20T17:12:04Z

Revision ID: 19cbb0b75e14
Revises: edf03ac61136
Create Date: 2026-03-20 20:12:05.223559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cbb0b75e14'
down_revision: Union[str, Sequence[str], None] = 'edf03ac61136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
