"""verify: 2026-03-19T19:22:50Z

Revision ID: 1f1ce3a5a117
Revises: d78a5908fab6
Create Date: 2026-03-19 22:22:50.671719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1ce3a5a117'
down_revision: Union[str, Sequence[str], None] = 'd78a5908fab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
