"""auto: 2026-03-19T21:10:41Z

Revision ID: 22c9eb085e1f
Revises: d815b055f451
Create Date: 2026-03-20 00:10:42.590263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c9eb085e1f'
down_revision: Union[str, Sequence[str], None] = 'd815b055f451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
