"""auto: 2026-03-19T16:01:10Z

Revision ID: 26674c9eeb1f
Revises: 63f61932cc68
Create Date: 2026-03-19 19:01:11.879693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26674c9eeb1f'
down_revision: Union[str, Sequence[str], None] = '63f61932cc68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_action_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('allow', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_action_grants_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_action_grants')),
    sa.UniqueConstraint('role_id', 'action', 'entity_type', name='uq_role_action_scope')
    )
    op.create_index(op.f('ix_role_action_grants_action'), 'role_action_grants', ['action'], unique=False)
    op.create_index(op.f('ix_role_action_grants_entity_type'), 'role_action_grants', ['entity_type'], unique=False)
    op.create_index(op.f('ix_role_action_grants_role_id'), 'role_action_grants', ['role_id'], unique=False)
    op.alter_column('approval_requests', 'reason',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('approval_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('approval_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_approval_requests_maker_id'), table_name='approval_requests')
    op.drop_constraint(op.f('uq_pending_unique'), 'approval_requests', type_='unique')
    op.drop_column('roles', 'is_system')
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.drop_constraint(op.f('fk_user_roles_user_id_users'), 'user_roles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_user_roles_user_id_users'), 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.add_column('roles', sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_pending_unique'), 'approval_requests', ['entity_type', 'entity_id', 'action', 'status'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_approval_requests_maker_id'), 'approval_requests', ['maker_id'], unique=False)
    op.alter_column('approval_requests', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('approval_requests', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('approval_requests', 'reason',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.drop_index(op.f('ix_role_action_grants_role_id'), table_name='role_action_grants')
    op.drop_index(op.f('ix_role_action_grants_entity_type'), table_name='role_action_grants')
    op.drop_index(op.f('ix_role_action_grants_action'), table_name='role_action_grants')
    op.drop_table('role_action_grants')
    # ### end Alembic commands ###
