"""verify: 2026-04-03T20:37:00Z

Revision ID: 2d4089c97ffc
Revises: a681a0b75423
Create Date: 2026-04-03 23:37:01.792656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4089c97ffc'
down_revision: Union[str, Sequence[str], None] = 'a681a0b75423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
