"""auto: 2026-03-19T19:00:41Z

Revision ID: 330686d22666
Revises: c9c4717ffdde
Create Date: 2026-03-19 22:00:42.588295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330686d22666'
down_revision: Union[str, Sequence[str], None] = 'c9c4717ffdde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Role', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
