"""verify: 2026-03-19T19:00:44Z

Revision ID: 332f4b6e7981
Revises: 330686d22666
Create Date: 2026-03-19 22:00:45.121731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332f4b6e7981'
down_revision: Union[str, Sequence[str], None] = '330686d22666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
