"""auto: 2026-03-19T20:25:39Z

Revision ID: 421a40bc6fb7
Revises: f24976b8ad79
Create Date: 2026-03-19 23:25:40.023804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '421a40bc6fb7'
down_revision: Union[str, Sequence[str], None] = 'f24976b8ad79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(op.f('fk_users_role_id_roles'), 'users', 'roles', ['role_id'], ['id'])
    # op.drop_column('users', 'Role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('Role', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # op.drop_constraint(op.f('fk_users_role_id_roles'), 'users', type_='foreignkey')
    # op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
