"""initial full schema

Revision ID: 4a0a537df5fc
Revises: 
Create Date: 2026-01-11 00:21:54.757699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0a537df5fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('Admin', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('Active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('Approved', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('Locked', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('Department', sa.String(length=255), nullable=False),
    sa.Column('Unit', sa.String(length=255), nullable=False),
    sa.Column('FirstName', sa.String(length=255), nullable=False),
    sa.Column('MiddleName', sa.String(length=255), nullable=False),
    sa.Column('LastName', sa.String(length=255), nullable=False),
    sa.Column('RssToken', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_Username'), 'users', ['Username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_Username'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
