"""auto: 2026-04-06T13:56:43Z

Revision ID: 4f8445f99e6e
Revises: 74f325a0e886
Create Date: 2026-04-06 16:56:43.966471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8445f99e6e'
down_revision: Union[str, Sequence[str], None] = '74f325a0e886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
