"""dev: autogenerate

Revision ID: 51689c5856e1
Revises: 
Create Date: 2026-01-12 12:53:58.482142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51689c5856e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('ProjectId', sa.Integer(), nullable=False),
    sa.Column('ProjectTemplateId', sa.Integer(), nullable=True),
    sa.Column('ProjectGroupId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Website', sa.String(length=2048), nullable=True),
    sa.Column('CreationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('Active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('WorkingHours', sa.Integer(), nullable=True),
    sa.Column('WorkingDays', sa.Integer(), nullable=True),
    sa.Column('NonWorkingHours', sa.Integer(), nullable=True),
    sa.Column('StartDate', sa.Date(), nullable=True),
    sa.Column('EndDate', sa.Date(), nullable=True),
    sa.Column('PercentComplete', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('ProjectId')
    )
    op.create_index(op.f('ix_projects_Name'), 'projects', ['Name'], unique=False)
    op.create_index(op.f('ix_projects_ProjectGroupId'), 'projects', ['ProjectGroupId'], unique=False)
    op.create_index(op.f('ix_projects_ProjectId'), 'projects', ['ProjectId'], unique=False)
    op.create_index(op.f('ix_projects_ProjectTemplateId'), 'projects', ['ProjectTemplateId'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('Admin', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('Active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('Approved', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('Locked', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('Department', sa.String(length=255), nullable=False),
    sa.Column('Unit', sa.String(length=255), nullable=False),
    sa.Column('FirstName', sa.String(length=255), nullable=False),
    sa.Column('MiddleName', sa.String(length=255), nullable=False),
    sa.Column('LastName', sa.String(length=255), nullable=False),
    sa.Column('RssToken', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_Username'), 'users', ['Username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_Username'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_ProjectTemplateId'), table_name='projects')
    op.drop_index(op.f('ix_projects_ProjectId'), table_name='projects')
    op.drop_index(op.f('ix_projects_ProjectGroupId'), table_name='projects')
    op.drop_index(op.f('ix_projects_Name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
