"""dev: autogenerate

Revision ID: 52f0b075d653
Revises: 
Create Date: 2026-01-15 19:35:39.015523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f0b075d653'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_template_id', sa.Integer(), nullable=True),
    sa.Column('project_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('working_hours', sa.Integer(), nullable=True),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('non_working_hours', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('percent_complete', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_group_id'), 'projects', ['project_group_id'], unique=False)
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_project_template_id'), 'projects', ['project_template_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=128), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('Admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('Active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('Approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('Locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('Department', sa.String(length=255), nullable=False),
    sa.Column('Unit', sa.String(length=255), nullable=False),
    sa.Column('FirstName', sa.String(length=255), nullable=False),
    sa.Column('MiddleName', sa.String(length=255), nullable=True),
    sa.Column('LastName', sa.String(length=255), nullable=False),
    sa.Column('RssToken', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_Username'), 'users', ['Username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_Username'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_template_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_group_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
