"""verify: 2026-03-20T17:40:04Z

Revision ID: 555112c79d2b
Revises: f7b9282fb7be
Create Date: 2026-03-20 20:40:04.991836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555112c79d2b'
down_revision: Union[str, Sequence[str], None] = 'f7b9282fb7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
