"""verify: 2026-04-04T23:37:20Z

Revision ID: 57ba6e09024b
Revises: 7b8680fa28ca
Create Date: 2026-04-05 02:37:21.053811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ba6e09024b'
down_revision: Union[str, Sequence[str], None] = '7b8680fa28ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
