"""auto: 2026-03-20T17:51:30Z

Revision ID: 6270c16a4db3
Revises: 74e329bea815
Create Date: 2026-03-20 20:51:31.403117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6270c16a4db3'
down_revision: Union[str, Sequence[str], None] = '74e329bea815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'action',
               existing_type=sa.TEXT(),
               type_=sa.Enum('create', 'update', 'execute', 'delete', 'login', 'logout', 'refresh', 'view', name='activity_action_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('activity_log', 'outcome',
               existing_type=postgresql.ENUM('success', 'failure', name='activity_outcome_enum'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'outcome',
               existing_type=postgresql.ENUM('success', 'failure', name='activity_outcome_enum'),
               server_default=sa.text("'success'::activity_outcome_enum"),
               existing_nullable=False)
    op.alter_column('activity_log', 'action',
               existing_type=sa.Enum('create', 'update', 'execute', 'delete', 'login', 'logout', 'refresh', 'view', name='activity_action_enum', native_enum=False),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
