"""auto: 2026-03-19T16:26:22Z

Revision ID: 62a946af12ff
Revises: 6d822048e269
Create Date: 2026-03-19 19:26:23.974088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a946af12ff'
down_revision: Union[str, Sequence[str], None] = '6d822048e269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
