"""verify: 2026-03-19T13:16:13Z

Revision ID: 63f61932cc68
Revises: c530c9aec79f
Create Date: 2026-03-19 16:16:14.501186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f61932cc68'
down_revision: Union[str, Sequence[str], None] = 'c530c9aec79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
