"""verify: 2026-03-19T12:08:41Z

Revision ID: 6844f82a351d
Revises: ea41904870a0
Create Date: 2026-03-19 15:08:42.946954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6844f82a351d'
down_revision: Union[str, Sequence[str], None] = 'ea41904870a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
