"""auto: 2026-03-19T16:16:37Z

Revision ID: 686859c00541
Revises: 072113fe2c64
Create Date: 2026-03-19 19:16:38.590903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686859c00541'
down_revision: Union[str, Sequence[str], None] = '072113fe2c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_actions'))
    )
    op.create_index(op.f('ix_role_actions_name'), 'role_actions', ['name'], unique=True)
    op.add_column('role_action_grants', sa.Column('action_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_role_action_grants_action'), table_name='role_action_grants')
    op.drop_constraint(op.f('uq_role_action_scope'), 'role_action_grants', type_='unique')
    op.create_unique_constraint('uq_role_action_scope', 'role_action_grants', ['role_id', 'action_id', 'entity_type'])
    op.create_index(op.f('ix_role_action_grants_action_id'), 'role_action_grants', ['action_id'], unique=False)
    op.create_foreign_key(op.f('fk_role_action_grants_action_id_role_actions'), 'role_action_grants', 'role_actions', ['action_id'], ['id'], ondelete='CASCADE')
    op.drop_column('role_action_grants', 'action')
    op.add_column('roles', sa.Column('is_default', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_default')
    op.add_column('role_action_grants', sa.Column('action', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_role_action_grants_action_id_role_actions'), 'role_action_grants', type_='foreignkey')
    op.drop_index(op.f('ix_role_action_grants_action_id'), table_name='role_action_grants')
    op.drop_constraint('uq_role_action_scope', 'role_action_grants', type_='unique')
    op.create_unique_constraint(op.f('uq_role_action_scope'), 'role_action_grants', ['role_id', 'action', 'entity_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_role_action_grants_action'), 'role_action_grants', ['action'], unique=False)
    op.drop_column('role_action_grants', 'action_id')
    op.drop_index(op.f('ix_role_actions_name'), table_name='role_actions')
    op.drop_table('role_actions')
    # ### end Alembic commands ###
