"""auto: 2026-03-20T17:44:54Z

Revision ID: 6975bec11666
Revises: 555112c79d2b
Create Date: 2026-03-20 20:44:55.124820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6975bec11666'
down_revision: Union[str, Sequence[str], None] = '555112c79d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'action',
               existing_type=postgresql.ENUM('create', 'update', 'view', 'execute', 'delete', 'login', 'logout', 'refresh', name='activity_action_enum'),
               type_=sa.Enum('create', 'update', 'execute', 'delete', 'login', 'logout', 'refresh', 'view', name='activity_action_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'action',
               existing_type=sa.Enum('create', 'update', 'execute', 'delete', 'login', 'logout', 'refresh', 'view', name='activity_action_enum', native_enum=False),
               type_=postgresql.ENUM('create', 'update', 'view', 'execute', 'delete', 'login', 'logout', 'refresh', name='activity_action_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
