"""auto: 2026-03-19T19:21:01Z

Revision ID: 69ef7e977681
Revises: c2d7239c5b8b
Create Date: 2026-03-19 22:21:02.080259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ef7e977681'
down_revision: Union[str, Sequence[str], None] = 'c2d7239c5b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
