"""verify: 2026-03-20T17:52:55Z

Revision ID: 6b0ad31c3439
Revises: 96ce9c24b37c
Create Date: 2026-03-20 20:52:56.347464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0ad31c3439'
down_revision: Union[str, Sequence[str], None] = '96ce9c24b37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
