"""auto: 2026-03-19T20:42:06Z

Revision ID: 6ed1534131b8
Revises: 421a40bc6fb7
Create Date: 2026-03-19 23:42:07.549063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6ed1534131b8'
down_revision: Union[str, Sequence[str], None] = '421a40bc6fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1) BACKFILL *ALL* NULLS FIRST
    op.execute("""
        UPDATE users
        SET username = COALESCE(username, 'user_' || id),
            email = COALESCE(email, 'user_' || id || '@example.com'),
            initials = COALESCE(initials, 'XX'),
            initials_colors = COALESCE(initials_colors, '#000000'),
            active = COALESCE(active, true),
            approved = COALESCE(approved, false),
            locked = COALESCE(locked, false),
            department = COALESCE(department, 'UNKNOWN'),
            unit = COALESCE(unit, 'UNKNOWN'),
            first_name = COALESCE(first_name, 'Unknown'),
            last_name = COALESCE(last_name, 'User'),
            role_id = COALESCE(role_id, 1)
    """)

    # 2) NOW IT IS SAFE TO MAKE COLUMNS NOT NULL
    op.alter_column('users', 'username', nullable=False)
    op.alter_column('users', 'email', nullable=False)
    op.alter_column('users', 'initials', nullable=False)
    op.alter_column('users', 'initials_colors', nullable=False)
    op.alter_column('users', 'active', nullable=False)
    op.alter_column('users', 'approved', nullable=False)
    op.alter_column('users', 'locked', nullable=False)
    op.alter_column('users', 'department', nullable=False)
    op.alter_column('users', 'unit', nullable=False)
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)
    op.alter_column('users', 'role_id', nullable=False)

    # 3) DROP ANY OLD CONSTRAINTS SAFELY
    for c in [
        'uq_users_Email', 'uq_users_Initials_colors', 'uq_users_Username',
        'uq_users_email', 'uq_users_username'
    ]:
        try:
            op.drop_constraint(c, 'users', type_='unique')
        except:
            pass

    # 4) RECREATE CLEAN UNIQUE CONSTRAINTS
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    op.create_unique_constraint('uq_users_initials_colors', 'users', ['initials_colors'])

    # 5) FK to roles table (safe even if exists)
    try:
        op.create_foreign_key(
            'fk_users_role_id_roles',
            'users', 'roles',
            ['role_id'], ['id']
        )
    except:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Role', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('MiddleName', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('Email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('FirstName', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('Initials', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('Approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                                     nullable=False))
    op.add_column('users', sa.Column('Initials_colors', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('Department', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('Username', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('LastName', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('Active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False,
                                     nullable=False))
    op.add_column('users', sa.Column('Unit', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('Locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                                     nullable=False))
    op.drop_constraint(op.f('fk_users_role_id_roles'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('uq_users_initials_colors'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['Username'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['Email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_Username'), 'users', ['Username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_Initials_colors'), 'users', ['Initials_colors'],
                                postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_Email'), 'users', ['Email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'unit')
    op.drop_column('users', 'department')
    op.drop_column('users', 'locked')
    op.drop_column('users', 'approved')
    op.drop_column('users', 'active')
    op.drop_column('users', 'email')
    op.drop_column('users', 'initials_colors')
    op.drop_column('users', 'initials')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
