"""auto: 2026-04-06T13:32:23Z

Revision ID: 729b9872dae5
Revises: cb8c7abde314
Create Date: 2026-04-06 16:32:24.153611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729b9872dae5'
down_revision: Union[str, Sequence[str], None] = 'cb8c7abde314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('template_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'template_id')
    # ### end Alembic commands ###
