"""auto: 2026-04-03T20:46:46Z

Revision ID: 73c93f93ac50
Revises: 2d4089c97ffc
Create Date: 2026-04-03 23:46:46.889943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c93f93ac50'
down_revision: Union[str, Sequence[str], None] = '2d4089c97ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
