"""verify: 2026-04-06T13:32:25Z

Revision ID: 74f325a0e886
Revises: 729b9872dae5
Create Date: 2026-04-06 16:32:25.929388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f325a0e886'
down_revision: Union[str, Sequence[str], None] = '729b9872dae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
