"""init: 2026-01-18T15:41:05Z

Revision ID: 76e39c8e8330
Revises: 
Create Date: 2026-01-18 15:41:05.787457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76e39c8e8330'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('workspace_type_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type_id', sa.Integer(), nullable=True),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('concurrency_guid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('custom_properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('guid', name=op.f('uq_portfolios_guid')),
    sa.UniqueConstraint('name', name=op.f('uq_portfolios_name'))
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_template_id', sa.Integer(), nullable=True),
    sa.Column('project_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('working_hours', sa.Integer(), nullable=True),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('non_working_hours', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('percent_complete', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=128), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('Admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('Active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('Approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('Locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('Department', sa.String(length=255), nullable=False),
    sa.Column('Unit', sa.String(length=255), nullable=False),
    sa.Column('FirstName', sa.String(length=255), nullable=False),
    sa.Column('MiddleName', sa.String(length=255), nullable=True),
    sa.Column('LastName', sa.String(length=255), nullable=False),
    sa.Column('RssToken', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('Email', name=op.f('uq_users_Email')),
    sa.UniqueConstraint('Username', name=op.f('uq_users_Username'))
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('project_template_id', sa.Integer(), nullable=True),
    sa.Column('workspace_type_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type_id', sa.Integer(), nullable=True),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('concurrency_guid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('custom_properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_programs_portfolio_id_portfolios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs')),
    sa.UniqueConstraint('guid', name=op.f('uq_programs_guid'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programs')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
