"""verify: 2026-04-06T14:21:17Z

Revision ID: 880f5fc062c1
Revises: 216f9d1ac31d
Create Date: 2026-04-06 17:21:18.481066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880f5fc062c1'
down_revision: Union[str, Sequence[str], None] = '216f9d1ac31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
