"""verify: 2026-03-19T16:26:25Z

Revision ID: 8d4fa4bcdf9e
Revises: 62a946af12ff
Create Date: 2026-03-19 19:26:26.484056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4fa4bcdf9e'
down_revision: Union[str, Sequence[str], None] = '62a946af12ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
