"""auto: 2026-03-20T17:52:53Z

Revision ID: 96ce9c24b37c
Revises: cd3d434a9707
Create Date: 2026-03-20 20:52:54.220173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ce9c24b37c'
down_revision: Union[str, Sequence[str], None] = 'cd3d434a9707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'outcome',
               existing_type=sa.TEXT(),
               server_default='success',
               type_=sa.Enum('success', 'failed', name='activity_outcome_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'outcome',
               existing_type=sa.Enum('success', 'failed', name='activity_outcome_enum', native_enum=False),
               server_default=None,
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
