"""verify: 2026-01-18T15:41:06Z

Revision ID: 9c7b653d863d
Revises: 76e39c8e8330
Create Date: 2026-01-18 15:41:07.048967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7b653d863d'
down_revision: Union[str, Sequence[str], None] = '76e39c8e8330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
