"""auto: 2026-04-03T20:36:58Z

Revision ID: a681a0b75423
Revises: 6b0ad31c3439
Create Date: 2026-04-03 23:36:59.256839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a681a0b75423'
down_revision: Union[str, Sequence[str], None] = '6b0ad31c3439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'outcome',
               existing_type=sa.TEXT(),
               type_=sa.Enum('success', 'failed', name='activity_outcome_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.drop_constraint(op.f('uq_users_initials_colors'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_initials_colors'), 'users', ['initials_colors'], postgresql_nulls_not_distinct=False)
    op.alter_column('activity_log', 'outcome',
               existing_type=sa.Enum('success', 'failed', name='activity_outcome_enum', native_enum=False),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    # ### end Alembic commands ###
