"""auto: 2026-01-18T15:42:36Z

Revision ID: b884dc8fbbd7
Revises: 9c7b653d863d
Create Date: 2026-01-18 15:42:37.028101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b884dc8fbbd7'
down_revision: Union[str, Sequence[str], None] = '9c7b653d863d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
