"""auto: 2026-03-19T21:10:50Z

Revision ID: bddb5579d3f8
Revises: dc1bad55b059
Create Date: 2026-03-20 00:10:50.731613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bddb5579d3f8'
down_revision: Union[str, Sequence[str], None] = 'dc1bad55b059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
