"""verify: 2026-03-19T19:17:20Z

Revision ID: be3c91f1b335
Revises: d5f12471d7de
Create Date: 2026-03-19 22:17:21.436832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3c91f1b335'
down_revision: Union[str, Sequence[str], None] = 'd5f12471d7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
