"""auto: 2026-03-19T19:18:34Z

Revision ID: c2d7239c5b8b
Revises: be3c91f1b335
Create Date: 2026-03-19 22:18:34.647938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c2d7239c5b8b'
down_revision: Union[str, Sequence[str], None] = 'be3c91f1b335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Role', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Role')
    # ### end Alembic commands ###
