"""verify: 2026-03-19T18:41:23Z

Revision ID: c9c4717ffdde
Revises: 7c56667e3a0a
Create Date: 2026-03-19 21:41:24.354921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c4717ffdde'
down_revision: Union[str, Sequence[str], None] = '7c56667e3a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
