"""auto: 2026-03-19T19:31:19Z

Revision ID: caa070a4a865
Revises: 1f1ce3a5a117
Create Date: 2026-03-19 22:31:20.531240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa070a4a865'
down_revision: Union[str, Sequence[str], None] = '1f1ce3a5a117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_user_roles_user_id_users'), 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_roles_user_id_users'), 'user_roles', type_='foreignkey')
    # ### end Alembic commands ###
