"""verify: 2026-04-05T00:00:41Z

Revision ID: cb8c7abde314
Revises: 0689ea77de52
Create Date: 2026-04-05 03:00:41.835400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8c7abde314'
down_revision: Union[str, Sequence[str], None] = '0689ea77de52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
