"""auto: 2026-03-19T19:17:19Z

Revision ID: d5f12471d7de
Revises: 332f4b6e7981
Create Date: 2026-03-19 22:17:19.856927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f12471d7de'
down_revision: Union[str, Sequence[str], None] = '332f4b6e7981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
