"""auto: 2026-03-19T20:50:00Z

Revision ID: d815b055f451
Revises: 6ed1534131b8
Create Date: 2026-03-19 23:50:00.785468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd815b055f451'
down_revision: Union[str, Sequence[str], None] = '6ed1534131b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'initials',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('users', 'initials_colors',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'unit',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'unit',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'initials_colors',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'initials',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
