"""verify: 2026-03-19T21:10:43Z

Revision ID: dc1bad55b059
Revises: 22c9eb085e1f
Create Date: 2026-03-20 00:10:44.040816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1bad55b059'
down_revision: Union[str, Sequence[str], None] = '22c9eb085e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
