"""verify: 2026-01-18T15:42:37Z

Revision ID: df06ec6d7f39
Revises: b884dc8fbbd7
Create Date: 2026-01-18 15:42:38.307261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df06ec6d7f39'
down_revision: Union[str, Sequence[str], None] = 'b884dc8fbbd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
