"""auto: 2026-03-19T12:08:38Z

Revision ID: ea41904870a0
Revises: 999ea88e258b
Create Date: 2026-03-19 15:08:39.862677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea41904870a0'
down_revision: Union[str, Sequence[str], None] = '999ea88e258b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolios', 'website',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.drop_index(op.f('ix_portfolios_category'), table_name='portfolios', postgresql_where='(category IS NOT NULL)')
    op.drop_constraint(op.f('uq_portfolios_name'), 'portfolios', type_='unique')
    op.drop_constraint(op.f('uq_users_Initials'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_Initials'), 'users', ['Initials'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_portfolios_name'), 'portfolios', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_portfolios_category'), 'portfolios', ['category'], unique=False, postgresql_where='(category IS NOT NULL)')
    op.alter_column('portfolios', 'website',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
