"""verify: 2026-03-19T21:10:51Z

Revision ID: ede500925ee3
Revises: bddb5579d3f8
Create Date: 2026-03-20 00:10:52.166084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede500925ee3'
down_revision: Union[str, Sequence[str], None] = 'bddb5579d3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
