"""verify: 2026-03-19T19:31:21Z

Revision ID: f24976b8ad79
Revises: caa070a4a865
Create Date: 2026-03-19 22:31:21.990550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24976b8ad79'
down_revision: Union[str, Sequence[str], None] = 'caa070a4a865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
