"""verify: 2026-04-03T20:46:47Z

Revision ID: f5432ee51d5f
Revises: 73c93f93ac50
Create Date: 2026-04-03 23:46:48.503275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5432ee51d5f'
down_revision: Union[str, Sequence[str], None] = '73c93f93ac50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
