"""auto: 2026-03-20T17:40:02Z

Revision ID: f7b9282fb7be
Revises: 19cbb0b75e14
Create Date: 2026-03-20 20:40:03.505598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b9282fb7be'
down_revision: Union[str, Sequence[str], None] = '19cbb0b75e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
